
---
branches: 100
checkCoverage: true
exclude: []
extension:
  - ts
functions: 100
instrument: true
lines: 100
reporter:
  - html
  - text-summary
  - text
require:
  - source-map-support/register
  - ts-node/register
sourceMap: true
statements: 100
